generator:
  class:                DbFinderAdminGenerator
  param:
    model_class:        sfSimpleBlogPost
    theme:              default
    css:                /sfSimpleBlogPlugin/css/admin.css

    list:
      title:            List of blog posts
      display:          [title, created_at, extract]
      with:             [<?php echo sfConfig::get('app_sfSimpleBlog_user_class', 'sfGuardUser')?>]
      layout:           stacked
      params:           %%_post%%
      filters:          [title, created_at]
      object_actions: 
        _edit:          ~
        togglePublish:  { name: publish/unpublish, action: togglePublish }
        toggleComment:  { name: enable/disable comments, action: toggleComment }
        _delete:        ~
        
    edit:
      title:            Edit post "%%title%%"
      display:          [author_id, title, extract, content, tags_as_string, allow_comments, is_published]
      fields:
        tags_as_string: { name: Tags, type: input_tag }
        content:        { params: size=60x30 <?php if(sfConfig::get('app_sfSimpleBlog_use_rich_text', false)): echo 'rich=true'; endif; ?> <?php if(sfConfig::get('app_sfSimpleBlog_use_media_library', false)): echo 'tinymce_options=\'file_browser_callback:"sfMediaLibrary.fileBrowserCallBack"\''; endif; ?> }
      actions: 
        _save:          ~
        togglePublish:  { name: publish/unpublish, action: togglePublish }
        _list:          ~
 